module idl {
  /*
  struct thrusterBowStruct {
    double inputForce;
    double inputAngle;
  };

  struct thrusterPortStruct {
    double inputForce;
    double inputAngle;
  };

  struct thrusterStarboardStruct {
    double inputForce;
    double inputAngle;
  };

  struct hullStruct {
    double inputWindSpeed;
    double inputWindAngle;
    double inputWaterCurrentSpeed;
    double inputWaterCurrentAngle;
    double inputWaveHeight; // TODO [5]
  };
  */

  struct DDSInput {
    float TBinputForce;
    float TBinputAngle;
    float TPinputForce;
    float TPinputAngle;
    float TSinputForce;
    float TSinputAngle;

    float inputWindSpeed;
    float inputWindAngle;
    float inputWaterCurrentSpeed;
    float inputWaterCurrentAngle;
    float inputWaveHeight[5];
  };

  struct DDSOutput {
    float outputHullPosition[6];
    float outputAntenna1Position[3];
    float outputAntenna2Position[3];
    float ouputVelocitySpeed;
    float outputVelocityAngle;
    float outputAccelerationLinear[3];
    float outputVelocityAngular[3];
  };

};
