module idl {
  struct thrusterBowStruct {
    double inputForce;
    double inputAngle;
  };

  struct thrusterPortStruct {
    double inputForce;
    double inputAngle;
  };

  struct thrusterStarboardStruct {
    double inputForce;
    double inputAngle;
  };

  struct hullStruct {
    double inputWindSpeed;
    double inputWindAngle;
    double inputWaterCurrentSpeed;
    double inputWaterCurrentAngle;
    double inputWaveHeight[5];
  };

  struct MyCustomSignalStructureInput {
    thrusterBowStruct thrusterBow;
    thrusterPortStruct thrusterPort;
    thrusterStarboardStruct thrusterStarboard;
    hullStruct hull;
  };

  struct MyCustomSignalStructureOutput {
    double outputHullPosition[6];
    double outputAntenna1Position[3];
    double outputAntenna2Position[3];
    double ouputVelocitySpeed;
    double outputVelocityAngle;
    double outputAccelerationLinear[3];
    double outputVelocityAngular[3];
  };

};
